# Generated by Django 5.0.6 on 2024-07-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProviders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(max_length=254)),
                ('location', models.CharField(max_length=200)),
                ('service', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=20)),
                ('zipcode', models.CharField(max_length=6)),
                ('password', models.CharField(max_length=200)),
                ('request_status', models.CharField(max_length=20)),
            ],
        ),
    ]
