# Generated by Django 5.0.7 on 2024-10-02 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceproviders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packagesmodel',
            old_name='profile_image',
            new_name='package_image',
        ),
    ]
