# Generated by Django 5.0.7 on 2024-08-21 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceproviders', '0001_providers_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_email', models.EmailField(max_length=254)),
                ('package_name', models.CharField(max_length=254)),
                ('package_id', models.CharField(max_length=100)),
                ('package_service', models.CharField(max_length=200)),
                ('package_price', models.IntegerField()),
            ],
        ),
    ]
