# Generated by Django 5.0.7 on 2024-10-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceproviders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRequestsModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=1000)),
                ('location', models.CharField(max_length=1000)),
                ('service_date', models.DateField()),
                ('package_name', models.CharField(max_length=1000)),
                ('package_id', models.IntegerField()),
                ('Company_id', models.IntegerField()),
                ('request_status', models.CharField(max_length=100)),
                ('OrderPersonId', models.CharField(max_length=1000)),
            ],
        ),
    ]
