# Generated by Django 5.0.7 on 2024-08-21 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceproviders', '0002_packagesmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddTeamModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_email', models.EmailField(max_length=254)),
                ('team_name', models.CharField(max_length=254)),
                ('team_member_email', models.EmailField(max_length=254)),
                ('team_member_name', models.CharField(max_length=254)),
                ('team_member_role', models.CharField(max_length=200)),
                ('team_member_phone', models.CharField(max_length=200)),
                ('team_member_cnic', models.IntegerField()),
            ],
        ),
    ]
