# Generated by Django 5.0.7 on 2024-08-21 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceproviders', '0003_addteammodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addteammodel',
            name='team_member_cnic',
            field=models.IntegerField(max_length=20),
        ),
    ]
