# Generated by Django 5.0.7 on 2024-10-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceproviders', '0003_orderrequestsmodal_package_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addteammodel',
            name='company_id',
            field=models.IntegerField(max_length=254),
        ),
        migrations.AlterField(
            model_name='orderrequestsmodal',
            name='Company_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orderrequestsmodal',
            name='package_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orderrequestsmodal',
            name='package_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='orderrequestsmodal',
            name='package_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='packagesmodel',
            name='company_id',
            field=models.IntegerField(max_length=254),
        ),
    ]
