# Generated by Django 5.0.7 on 2024-08-23 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceproviders', '0005_alter_addteammodel_team_member_cnic'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagesmodel',
            name='package_image',
            field=models.ImageField(default='default_image.jpg', upload_to='images/packageImages/'),
        ),
    ]
