# Generated by Django 5.0.7 on 2024-10-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceproviders', '0005_alter_addteammodel_company_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedOrdersModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=1000)),
                ('location', models.CharField(max_length=1000)),
                ('service_date', models.DateField()),
                ('package_id', models.CharField(default='', max_length=1000)),
                ('package_price', models.CharField(default='', max_length=1000)),
                ('team_name', models.CharField(max_length=1000)),
            ],
        ),
    ]
