# Generated by Django 5.0.7 on 2024-08-23 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceproviders', '0006_packagesmodel_package_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagesmodel',
            name='package_image',
            field=models.FileField(default='default_image.jpg', upload_to='images/packageImages/'),
        ),
    ]
