# Generated by Django 5.0.7 on 2024-10-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceproviders', '0006_approvedordersmodal'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvedordersmodal',
            name='order_status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
