# Generated by Django 5.0.7 on 2024-10-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceproviders', '0008_approvedordersmodal_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='addteammodel',
            name='team_member_occupation',
            field=models.CharField(default='', max_length=200),
        ),
    ]
