# Generated by Django 5.0.7 on 2024-08-24 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceproviders', '0008_remove_packagesmodel_package_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagesmodel',
            name='package_id',
        ),
    ]
