# Generated by Django 5.0.7 on 2024-10-02 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentRentAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartmentImage', models.ImageField(upload_to='images/RentApartment/')),
                ('country', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('desciption', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('apartmentType', models.CharField(max_length=200)),
                ('aprtmentSize', models.CharField(max_length=200)),
                ('floorNumber', models.CharField(max_length=200)),
                ('bedrooms', models.CharField(max_length=200)),
                ('bathrooms', models.CharField(max_length=200)),
                ('furnishing', models.CharField(max_length=200)),
                ('ownerName', models.CharField(max_length=200)),
                ('ownerNumber', models.CharField(max_length=200)),
                ('ownerEmail', models.EmailField(max_length=200)),
                ('RequestStatus', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HouseRentAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('houseImage', models.ImageField(upload_to='images/RentHouse/')),
                ('country', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('houseType', models.CharField(max_length=200)),
                ('builtYear', models.CharField(max_length=200)),
                ('bedrooms', models.CharField(max_length=200)),
                ('bathrooms', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=200)),
                ('furnishing', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('houseDescription', models.CharField(max_length=200)),
                ('ownerName', models.CharField(max_length=200)),
                ('ownerNumber', models.CharField(max_length=200)),
                ('ownerEmail', models.CharField(max_length=200)),
                ('RequestStatus', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OfficeRentAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officeImage', models.ImageField(upload_to='images/RentOffice/')),
                ('country', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('desciption', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('officeType', models.CharField(max_length=200)),
                ('officeSize', models.CharField(max_length=200)),
                ('floorNumber', models.CharField(max_length=200)),
                ('buildingType', models.CharField(max_length=200)),
                ('ownerName', models.CharField(max_length=200)),
                ('ownerNumber', models.CharField(max_length=200)),
                ('ownerEmail', models.EmailField(max_length=200)),
                ('RequestStatus', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
