# Generated by Django 5.0.7 on 2024-09-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=10),
        ),
    ]
