# Generated by Django 5.0.7 on 2024-11-06 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('propertyType', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('price_per_month', models.CharField(max_length=200)),
                ('ownerName', models.CharField(max_length=200)),
                ('ownerNumber', models.CharField(max_length=200)),
                ('ownerEmail', models.EmailField(max_length=200)),
                ('requestStatus', models.CharField(max_length=200)),
                ('furnishing', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=200)),
                ('houseType', models.CharField(blank=True, max_length=200, null=True)),
                ('builtYear', models.CharField(blank=True, max_length=4, null=True)),
                ('bedrooms', models.CharField(blank=True, max_length=200, null=True)),
                ('bathrooms', models.CharField(blank=True, max_length=200, null=True)),
                ('area', models.CharField(blank=True, max_length=200, null=True)),
                ('officeType', models.CharField(blank=True, max_length=200, null=True)),
                ('officeSize', models.CharField(blank=True, max_length=200, null=True)),
                ('floorNumber', models.CharField(blank=True, max_length=200, null=True)),
                ('buildingType', models.CharField(blank=True, max_length=200, null=True)),
                ('apartmentType', models.CharField(blank=True, max_length=200, null=True)),
                ('apartmentSize', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RentAdImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/RentProperties/')),
                ('rent_ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Admin.rentad')),
            ],
        ),
        migrations.DeleteModel(
            name='ApartmentRentAd',
        ),
        migrations.DeleteModel(
            name='HouseRentAd',
        ),
        migrations.DeleteModel(
            name='OfficeRentAd',
        ),
        migrations.AddField(
            model_name='users',
            name='status',
            field=models.CharField(default='Active', max_length=200),
        ),
    ]
