# Generated by Django 5.0.7 on 2024-09-25 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_alter_users_email_alter_users_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=200),
        ),
    ]
