# Generated by Django 5.0.7 on 2024-10-16 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MessageSystem', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminProviderMessageModal',
            new_name='AdminMessageModal',
        ),
        migrations.RenameModel(
            old_name='AdminUserMessageModal',
            new_name='ProviderMessageModal',
        ),
        migrations.RenameModel(
            old_name='ProviderUserMessageModal',
            new_name='UserMessageModal',
        ),
    ]
