# Generated by Django 5.0.7 on 2024-10-17 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MessageSystem', '0002_rename_adminprovidermessagemodal_adminmessagemodal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminmessagemodal',
            old_name='receiver_id',
            new_name='receiverId',
        ),
        migrations.RenameField(
            model_name='adminmessagemodal',
            old_name='receiver_name',
            new_name='receiverName',
        ),
        migrations.RenameField(
            model_name='adminmessagemodal',
            old_name='sender_id',
            new_name='senderId',
        ),
        migrations.RenameField(
            model_name='adminmessagemodal',
            old_name='sender_name',
            new_name='senderName',
        ),
    ]
